class Orders {
  final int id;
  final int userId;
  final int storesId;
  final int paymentId;
  final int count;
  final String comment;
  final DateTime createdAt;
  final String state;
  final String reason;
  final bool isClosure;

  Orders({
    required this.id,
    required this.userId,
    required this.storesId,
    required this.paymentId,
    required this.count,
    required this.comment,
    required this.createdAt,
    required this.state,
    required this.reason,
    required this.isClosure,
  });
}

List<Orders> orderList = [
  Orders(
    id: 1,
    userId: 1,
    storesId: 1,
    paymentId: 1,
    count: 2,
    comment: '3인분 같은 2인분으로 주세용~',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 2,
    userId: 2,
    storesId: 2,
    paymentId: 2,
    count: 3,
    comment: '4인분 같은 3인분으로 주세용~',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 3,
    userId: 3,
    storesId: 3,
    paymentId: 3,
    count: 20,
    comment: '벨 누르지 말아주세요',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 4,
    userId: 1,
    storesId: 1,
    paymentId: 1,
    count: 2,
    comment: '3인분 같은 2인분으로 주세용~',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 5,
    userId: 2,
    storesId: 2,
    paymentId: 2,
    count: 3,
    comment: '4인분 같은 3인분으로 주세용~',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 6,
    userId: 3,
    storesId: 3,
    paymentId: 3,
    count: 20,
    comment: '벨 누르지 말아주세요',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 7,
    userId: 1,
    storesId: 1,
    paymentId: 1,
    count: 2,
    comment: '3인분 같은 2인분으로 주세용~',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 8,
    userId: 2,
    storesId: 2,
    paymentId: 2,
    count: 3,
    comment: '4인분 같은 3인분으로 주세용~',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 9,
    userId: 3,
    storesId: 3,
    paymentId: 3,
    count: 20,
    comment: '벨 누르지 말아주세요',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 10,
    userId: 1,
    storesId: 1,
    paymentId: 1,
    count: 2,
    comment: '3인분 같은 2인분으로 주세용~',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 11,
    userId: 2,
    storesId: 2,
    paymentId: 2,
    count: 3,
    comment: '4인분 같은 3인분으로 주세용~',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
  Orders(
    id: 12,
    userId: 3,
    storesId: 3,
    paymentId: 3,
    count: 20,
    comment: '벨 누르지 말아주세요',
    createdAt: DateTime.now(),
    state: '진행중',
    reason: '뭐야 이거',
    isClosure: false,
  ),
];
